<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>MacBookEco.PlatformSecurity.Tests</AssemblyName>
    <RootNamespace>MacBookEco</RootNamespace>
    <OutputPath>..\build\out\tests\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="mscorlib" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Management" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\tests\Platform.Security\Program.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="MacBookEco.Admin.csproj" />
  </ItemGroup>
</Project>
